// @generated by scripts/generate_doc_data.py -- DO NOT EDIT BY HAND.
// Source of truth: artifacts/research_summary.json (reference variant) +
// force-tracked metadata artifacts. Regenerate with:
//   uv run python scripts/generate_doc_data.py repo-facts
// Verified by web/src/client/learn/repo-facts.test.ts and `make check-docs`.

export const repoFacts = {
  totalValidRespondents: 603322,
  trainRows: 422326,
  valRows: 90498,
  testRows: 90498,
  firstItemId: "ext3",
  firstItemText: "I feel comfortable around people.",
  firstItemCrossDomainInfo: 1.5457,
  splitScheme: "random",
  baselineK20: {
    domainBalancedR: 0.9277,
    domainBalancedMae: 8.13,
    miniIpipStandaloneR: 0.9068,
    adaptiveTopKR: 0.8225,
    constrainedAdaptiveR: 0.9066,
  },
  mlVsAveragingK20: {
    domainBalanced: {
      mlR: 0.9277,
      avgR: 0.9214,
      deltaR: 0.0063,
    },
    miniIpip: {
      mlR: 0.918,
      avgR: 0.9068,
      deltaR: 0.0113,
    },
  },
  validation: {
    full50R: 0.9997,
    full50Mae: 0.51,
    full50Coverage: 0.926,
    sparse20R: 0.9107,
    sparse20Mae: 8.96,
    sparse20Coverage: 0.8977,
  },
  simulation: {
    overallR: 0.9273,
    overallMae: 8.16,
    overallCoverage: 0.8947,
    meanItemsPerDomain: 4,
    meanItemsTotal: 20,
  },
  norms: {
    ext: {
      mean: 2.9146,
      sd: 0.9112,
    },
    agr: {
      mean: 3.759,
      sd: 0.7366,
    },
    csn: {
      mean: 3.3426,
      sd: 0.739,
    },
    est: {
      mean: 2.919,
      sd: 0.8611,
    },
    opn: {
      mean: 3.9387,
      sd: 0.6183,
    },
  },
  interItemRBar: {
    ext: 0.4691,
    agr: 0.3557,
    csn: 0.3145,
    est: 0.4079,
    opn: 0.2866,
  },
  greedyTopK20ItemsPerDomain: {
    ext: 9,
    agr: 3,
    csn: 2,
    est: 6,
    opn: 0,
  },
  currentLockedParams: {
    n_estimators: 9056,
    max_depth: 5,
    learning_rate: 0.010650800669570068,
    reg_alpha: 4.612409189436812,
    reg_lambda: 4.564386465772608,
    subsample: 0.6507981007390146,
    colsample_bytree: 0.5291846507889049,
    min_child_weight: 4,
  },
} as const;
