/**
 * Cross-runtime numerical parity: the TypeScript runtime must reproduce the
 * committed golden vectors (generated by the Python reference runtime from the
 * SAME tests/fixtures/golden/model.onnx + config.json) within tolerance.
 *
 * Together with tests/test_fixture_stable.py (Python) and
 * web/src/server/golden.test.ts (web), this locks Python == TypeScript == web.
 * The fixture is committed, so this runs in CI with no external artifacts.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import { IPIPBFFMPredictor, calibrationRegime } from "./inference.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR =
  process.env.BFFM_FIXTURE_DIR ??
  resolve(__dirname, "..", "tests", "fixtures", "golden");
const HAS_FIXTURE = existsSync(resolve(FIXTURE_DIR, "config.json"));
const REQUIRE_ARTIFACTS = process.env.REQUIRE_ARTIFACTS === "1";

if (REQUIRE_ARTIFACTS && !HAS_FIXTURE) {
  throw new Error(
    `REQUIRE_ARTIFACTS=1 but the golden fixture is missing at ${FIXTURE_DIR}`
  );
}

const DOMAINS = ["ext", "agr", "csn", "est", "opn"] as const;
const QUANTILES = ["q05", "q50", "q95"] as const;
const N_FEATURES = 50;

interface Golden {
  tolerance: { raw_atol: number; percentile_atol: number };
  inputs: Record<string, { array?: (number | null)[]; items?: Record<string, number> }>;
  expected: Record<
    string,
    Record<string, { raw: Record<string, number>; percentile: Record<string, number> }>
  >;
}

const golden: Golden | null = HAS_FIXTURE
  ? JSON.parse(readFileSync(resolve(FIXTURE_DIR, "golden_vectors.json"), "utf-8"))
  : null;

describe.skipIf(!HAS_FIXTURE)("Tri-runtime golden-vector parity (TypeScript)", () => {
  it("reproduces every golden vector within tolerance", async () => {
    const g = golden!;
    // Floor guard: a malformed regen emitting {inputs:{}} must not pass vacuously.
    expect(Object.keys(g.inputs).length).toBeGreaterThanOrEqual(6);
    const predictor = await IPIPBFFMPredictor.create(FIXTURE_DIR);
    try {
      for (const [name, spec] of Object.entries(g.inputs)) {
        let result;
        if (spec.array) {
          const arr = new Float32Array(spec.array.map((v) => (v === null ? NaN : v)));
          result = await predictor.predictArray(arr);
        } else {
          result = await predictor.predict(spec.items!);
        }
        for (const d of DOMAINS) {
          for (const q of QUANTILES) {
            const exp = g.expected[name][d];
            expect(Math.abs(result[d].raw[q] - exp.raw[q])).toBeLessThanOrEqual(
              g.tolerance.raw_atol
            );
            expect(
              Math.abs(result[d].percentile[q] - exp.percentile[q])
            ).toBeLessThanOrEqual(g.tolerance.percentile_atol);
          }
        }
      }
    } finally {
      predictor.dispose();
    }
  });
});

describe("Calibration regime boundary", () => {
  function arrayWithAnswered(n: number): Float32Array {
    const arr = new Float32Array(N_FEATURES).fill(NaN);
    for (let i = 0; i < n; i++) arr[i] = 3.0;
    return arr;
  }

  it("50 answered → full_50", () => {
    expect(calibrationRegime(arrayWithAnswered(50))).toBe("full_50");
  });

  it("49 answered → sparse_20_balanced", () => {
    expect(calibrationRegime(arrayWithAnswered(49))).toBe("sparse_20_balanced");
  });

  it("NaN entries are not counted as answered", () => {
    // 49 real answers + 1 NaN must stay sparse, not flip to full_50.
    const arr = arrayWithAnswered(49);
    arr[49] = NaN;
    expect(calibrationRegime(arr)).toBe("sparse_20_balanced");
  });
});
