"""WS1: drift tripwire for the committed, generated model cards.

``output/reference/README.md`` (the reference model card) and ``output/README.md``
(the repo readme) are generated by ``pipeline/11_export_onnx.py`` from the
per-variant evaluation artifacts. Those per-variant inputs are *gitignored*, so
``make check-docs`` cannot regenerate-and-diff the cards the way it does for the
fence docs / repoFacts. The result is a coverage gap: a retrain that never re-ran
``make refresh-docs`` would leave a stale card committed with nothing to catch it.

This test closes that gap from the other direction: it reads the committed cards
and asserts their headline model-derived numbers still agree with the *tracked*
source of truth (``artifacts/research_summary.json`` + the force-tracked split /
tuned-params artifacts). A retrain that moves a value but forgets to regenerate
the card fails here. (Rounding is tolerated; only real drift trips it.)
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
RESEARCH_SUMMARY = ROOT / "artifacts" / "research_summary.json"
SPLIT_METADATA = ROOT / "data" / "processed" / "canonical_v1" / "split_metadata.json"
TUNED_PARAMS = ROOT / "artifacts" / "tuned_params.json"
REFERENCE_CARD = ROOT / "output" / "reference" / "README.md"
REPO_README = ROOT / "output" / "README.md"

_REQUIRED = [RESEARCH_SUMMARY, SPLIT_METADATA, TUNED_PARAMS, REFERENCE_CARD, REPO_README]
pytestmark = pytest.mark.skipif(
    not all(p.exists() for p in _REQUIRED),
    reason="model cards or tracked source artifacts not present",
)

# Tolerances: r/coverage cards round to 3-4 dp / 1 dp, so a benign rounding
# straddle is < ~5e-4 / 0.05pp. A real retrain drift is far larger; these
# tolerances catch drift without tripping on a rounding boundary.
_R_TOL = 1.5e-3
_PCT_TOL = 0.06


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _find_float(pattern: str, text: str, label: str) -> float:
    m = re.search(pattern, text)
    assert m, f"could not locate {label} in card (pattern {pattern!r}); card layout changed?"
    return float(m.group(1).replace(",", ""))


def test_reference_card_perf_table_matches_artifacts():
    card = REFERENCE_CARD.read_text(encoding="utf-8")
    ref = _load(RESEARCH_SUMMARY)["variants"]["reference"]
    k20 = ref["baselines"]["k20"]

    cases = [
        ("Full assessment", 50, ref["validation"]["full_50"]["pearson_r"]),
        ("Domain-balanced", 20, k20["domain_balanced"]["pearson_r"]),
        ("Mini-IPIP mapping", 20, k20["mini_ipip"]["pearson_r"]),
        ("Greedy top-K", 20, k20["adaptive_topk"]["pearson_r"]),
    ]
    for label, k, expected in cases:
        shown = _find_float(rf"{re.escape(label)}\s*\|\s*{k}\s*\|[^|]*\|\s*([0-9.]+)", card, f"{label} r")
        assert abs(shown - expected) <= _R_TOL, (
            f"{label}@K={k}: card shows {shown}, artifacts say {expected:.6f} "
            "(stale card? run `make refresh-docs`)"
        )


def test_reference_card_hyperparameters_match_tuned_params():
    card = REFERENCE_CARD.read_text(encoding="utf-8")
    hp = _load(TUNED_PARAMS)["hyperparameters"]
    m = re.search(r"n_estimators=(\d+), max_depth=(\d+), learning_rate=([0-9.]+)", card)
    assert m, "hyperparameter line not found in reference card"
    assert int(m.group(1)) == hp["n_estimators"]
    assert int(m.group(2)) == hp["max_depth"]
    assert float(m.group(3)) == round(float(hp["learning_rate"]), 4)


def test_reference_card_training_n_matches_split():
    card = REFERENCE_CARD.read_text(encoding="utf-8")
    train_rows = _load(SPLIT_METADATA)["train_rows"]
    shown = int(_find_float(r"n = ([\d,]+)", card, "training n"))
    assert shown == train_rows


def test_reference_card_norms_match_artifacts():
    card = REFERENCE_CARD.read_text(encoding="utf-8")
    norms = _load(RESEARCH_SUMMARY)["reference_notes_inputs"]["norms"]["norms"]
    labels = {
        "Extraversion": "ext",
        "Agreeableness": "agr",
        "Conscientiousness": "csn",
        "Emotional Stability": "est",
        "Intellect/Imagination": "opn",
    }
    for label, dom in labels.items():
        m = re.search(rf"{re.escape(label)}\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|", card)
        assert m, f"norms row for {label} not found in reference card"
        mean_shown, sd_shown = float(m.group(1)), float(m.group(2))
        assert abs(mean_shown - norms[dom]["mean"]) <= _R_TOL, f"{label} mean drift"
        assert abs(sd_shown - norms[dom]["sd"]) <= _R_TOL, f"{label} sd drift"


def test_domain_table_rows_byte_identical_to_prior_card_literals():
    """WS4: the model-card domain table is now built from lib.constants, but must
    render byte-identically to the prior hardcoded rows (the committed reference
    card is not regenerated here, so this locks the substitution)."""
    from lib.constants import DOMAIN_DISPLAY_LABELS, DOMAINS, ITEMS_PER_DOMAIN

    rows = [
        [DOMAIN_DISPLAY_LABELS[d], f"`{d}`", f"{d}1-{d}{ITEMS_PER_DOMAIN}"]
        for d in DOMAINS
    ]
    assert rows == [
        ["Extraversion", "`ext`", "ext1-ext10"],
        ["Agreeableness", "`agr`", "agr1-agr10"],
        ["Conscientiousness", "`csn`", "csn1-csn10"],
        ["Emotional Stability", "`est`", "est1-est10"],
        ["Intellect/Imagination", "`opn`", "opn1-opn10"],
    ]
    # And the committed reference card still contains exactly those rows.
    card = REFERENCE_CARD.read_text(encoding="utf-8")
    for label, code, items in rows:
        assert re.search(
            rf"{re.escape(label)}\s*\|\s*{re.escape(code)}\s*\|\s*{re.escape(items)}",
            card,
        ), f"reference card domain-table row for {label} missing/changed"


def test_repo_readme_coverage_and_n_match_artifacts():
    readme = REPO_README.read_text(encoding="utf-8")
    summary = _load(RESEARCH_SUMMARY)
    ref = summary["variants"]["reference"]

    deployed_cov = ref["baselines"]["k20"]["domain_balanced"]["coverage_90"] * 100
    sparse_cov = ref["validation"]["sparse_20"]["coverage_90"] * 100
    full_cov = ref["validation"]["full_50"]["coverage_90"] * 100

    shown_deployed = _find_float(r"approximately ([0-9.]+)% for the deployed domain-balanced", readme, "deployed coverage")
    shown_sparse = _find_float(r"approximately ([0-9.]+)% for the sparse_20_balanced", readme, "sparse coverage")
    shown_full = _find_float(r"approximately ([0-9.]+)% for the full_50", readme, "full coverage")

    assert abs(shown_deployed - deployed_cov) <= _PCT_TOL, "deployed coverage drift in repo readme"
    assert abs(shown_sparse - sparse_cov) <= _PCT_TOL, "sparse coverage drift in repo readme"
    assert abs(shown_full - full_cov) <= _PCT_TOL, "full coverage drift in repo readme"

    train_rows = _load(SPLIT_METADATA)["train_rows"]
    shown_n = int(_find_float(r"n = ([\d,]+)", readme, "training n"))
    assert shown_n == train_rows
