"""Tests for lib/constants.py — validate structural invariants."""

import json
from pathlib import Path

import pytest

from lib.constants import (
    DEFAULT_PARAMS,
    DOMAIN_CSV_TO_INTERNAL,
    DOMAIN_LABELS,
    DOMAINS,
    ITEM_COLUMNS,
    ITEMS_PER_DOMAIN,
    QUANTILE_NAME_LIST,
    QUANTILE_NAMES,
    QUANTILES,
    REVERSE_KEYED,
)

_PACKAGE_ROOT = Path(__file__).resolve().parent.parent
_CANONICAL_ITEMS = _PACKAGE_ROOT / "tests" / "fixtures" / "golden" / "canonical_items.json"
_ITEM_INFO = _PACKAGE_ROOT / "data" / "processed" / "canonical_v1" / "item_info.json"


def _expected_reverse_keyed(item_id: str) -> bool:
    """Reverse-keying for an item id per REVERSE_KEYED (the authoritative source)."""
    code = item_id[:3]
    number = int(item_id[3:])
    csv_domain = next(k for k, v in DOMAIN_CSV_TO_INTERNAL.items() if v == code)
    return number in REVERSE_KEYED[csv_domain]


class TestQuantileNameList:
    def test_matches_quantile_names_in_order(self):
        assert QUANTILE_NAME_LIST == [QUANTILE_NAMES[q] for q in QUANTILES]

    def test_is_the_expected_triple(self):
        assert QUANTILE_NAME_LIST == ["q05", "q50", "q95"]


class TestCanonicalItemsFixture:
    """The committed canonical_items.json fixture is the cross-runtime source of
    truth for the deployed 20-item form; lock it to lib.constants and (when
    present) to the pipeline's own domain_balanced selection."""

    def _load(self) -> dict:
        return json.loads(_CANONICAL_ITEMS.read_text())

    def test_has_twenty_items_four_per_domain(self):
        fixture = self._load()
        ids = fixture["domain_balanced_20"]
        assert len(ids) == 20
        for domain in DOMAINS:
            assert sum(1 for i in ids if i[:3] == domain) == 4

    def test_reverse_key_flags_match_constants(self):
        fixture = self._load()
        for item_id, flag in fixture["reverse_keyed"].items():
            assert flag == _expected_reverse_keyed(item_id), item_id

    def test_set_matches_pipeline_selection_when_item_info_present(self):
        if not _ITEM_INFO.exists():
            pytest.skip("item_info.json absent (regenerated by stage 05 / Part C)")
        pool = json.loads(_ITEM_INFO.read_text())["itemPool"]
        selected: list[str] = []
        for domain in DOMAINS:
            items = [it for it in pool if it["homeDomain"] == domain]
            items.sort(key=lambda x: abs(x.get("ownDomainR", 0.0)), reverse=True)
            selected.extend(it["id"] for it in items[:4])
        assert set(self._load()["domain_balanced_20"]) == set(selected)


class TestDomainStructure:
    def test_five_domains(self):
        assert len(DOMAINS) == 5

    def test_items_per_domain_is_10(self):
        assert ITEMS_PER_DOMAIN == 10

    def test_total_item_columns(self):
        assert len(ITEM_COLUMNS) == 50

    def test_column_naming_convention(self):
        """Each column matches {domain}{1-10}."""
        for domain in DOMAINS:
            for i in range(1, ITEMS_PER_DOMAIN + 1):
                assert f"{domain}{i}" in ITEM_COLUMNS

    def test_domain_labels_cover_all_domains(self):
        assert set(DOMAIN_LABELS.keys()) == set(DOMAINS)


class TestQuantileConfig:
    def test_quantile_names_maps_all_quantiles(self):
        assert set(QUANTILE_NAMES.keys()) == set(QUANTILES)

    def test_quantiles_sorted_ascending(self):
        assert QUANTILES == sorted(QUANTILES)


class TestReverseKeyed:
    def test_indices_valid_range(self):
        """All reverse-keyed indices are between 1 and ITEMS_PER_DOMAIN."""
        for domain_key, indices in REVERSE_KEYED.items():
            for idx in indices:
                assert 1 <= idx <= ITEMS_PER_DOMAIN, (
                    f"{domain_key} index {idx} out of range"
                )

    def test_keys_map_to_domains(self):
        """All REVERSE_KEYED keys correspond to a domain (via CSV mapping)."""
        for key in REVERSE_KEYED:
            assert key in DOMAIN_CSV_TO_INTERNAL, f"{key} not in CSV mapping"


class TestDefaultParams:
    def test_expected_xgboost_keys(self):
        expected = {
            "n_estimators",
            "max_depth",
            "learning_rate",
            "reg_alpha",
            "reg_lambda",
            "subsample",
            "colsample_bytree",
            "min_child_weight",
        }
        assert expected.issubset(set(DEFAULT_PARAMS.keys()))
