#!/usr/bin/env python3
"""Generate doc data from the reference source-of-truth artifacts.

Single source of truth: ``artifacts/research_summary.json`` (variant-aware;
reference data under ``reference_notes_inputs`` plus ``variants.reference``)
together with the force-tracked metadata artifacts
(``data/processed/load_metadata.json``,
``data/processed/canonical_v1/{split_metadata,first_item}.json``,
``artifacts/tuned_params.json``, ``artifacts/ipip_bffm_norms.json``).

Every model-derived value shown in a doc must be GENERATED from these
artifacts, never hand-typed. Pure design constants that can never change
between runs (5 domains, 1-5 Likert scale, tau=0.05/0.50/0.95, item counts
like 50/20/4) stay inline in the prose.

Two modes:

``repo-facts``
    Emit ``web/src/client/learn/content/repo-facts.generated.ts`` --
    an ``export const repoFacts = {...} as const;`` built from the
    reference artifacts. ``data.ts`` re-exports it (MECHANISM 1).

``inject``
    Scan a configured set of ``.md`` files for fenced blocks
    ``<!-- BEGIN GENERATED: <key> -->`` ... ``<!-- END GENERATED: <key> -->``
    and replace the inner content with the rendered block for ``<key>``
    (MECHANISM 2). Prose OUTSIDE the fences stays hand-edited.

Usage::

    uv run python scripts/generate_doc_data.py repo-facts
    uv run python scripts/generate_doc_data.py inject
    uv run python scripts/generate_doc_data.py repo-facts --check   # diff only
    uv run python scripts/generate_doc_data.py inject --check
    uv run python scripts/generate_doc_data.py all                  # both modes
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

PACKAGE_ROOT = Path(__file__).resolve().parent.parent

ARTIFACTS_DIR = PACKAGE_ROOT / "artifacts"
DATA_PROCESSED_DIR = PACKAGE_ROOT / "data" / "processed"
CANONICAL_DIR = DATA_PROCESSED_DIR / "canonical_v1"

RESEARCH_SUMMARY_PATH = ARTIFACTS_DIR / "research_summary.json"
LOAD_METADATA_PATH = DATA_PROCESSED_DIR / "load_metadata.json"
SPLIT_METADATA_PATH = CANONICAL_DIR / "split_metadata.json"
FIRST_ITEM_PATH = CANONICAL_DIR / "first_item.json"
TUNED_PARAMS_PATH = ARTIFACTS_DIR / "tuned_params.json"
NORMS_PATH = ARTIFACTS_DIR / "ipip_bffm_norms.json"

REPO_FACTS_OUT = (
    PACKAGE_ROOT / "web" / "src" / "client" / "learn" / "content" / "repo-facts.generated.ts"
)

# Markdown files scanned for GENERATED fences. Add any .md that cites model
# numbers here; only files with at least one fence are rewritten.
MARKDOWN_TARGETS = [
    PACKAGE_ROOT / "README.md",
    PACKAGE_ROOT / "docs" / "inference.md",
    PACKAGE_ROOT / "docs" / "infrastructure.md",
    PACKAGE_ROOT / "docs" / "pipeline.md",
    PACKAGE_ROOT / "docs" / "research.md",
]

# Design constants (never change between runs). Domain order is the canonical
# lib/constants.py DOMAINS order; labels match the published docs.
DOMAIN_ORDER = ["ext", "agr", "csn", "est", "opn"]
DOMAIN_LABELS = {
    "ext": "Extraversion",
    "agr": "Agreeableness",
    "csn": "Conscientiousness",
    "est": "Emotional Stability",
    "opn": "Intellect/Imagination",
}

GENERATED_HEADER = (
    "// @generated by scripts/generate_doc_data.py -- DO NOT EDIT BY HAND.\n"
    "// Source of truth: artifacts/research_summary.json (reference variant) +\n"
    "// force-tracked metadata artifacts. Regenerate with:\n"
    "//   uv run python scripts/generate_doc_data.py repo-facts\n"
    "// Verified by web/src/client/learn/repo-facts.test.ts and `make check-docs`.\n"
)


# --------------------------------------------------------------------------- #
# Artifact loading
# --------------------------------------------------------------------------- #
_CONFLICT_MARKER_RE = re.compile(r"^(<<<<<<< |=======$|>>>>>>> )", re.MULTILINE)


def _load_json(path: Path) -> dict[str, Any]:
    """Load a source artifact, re-raising a clear, actionable diagnostic.

    A bare FileNotFoundError/JSONDecodeError traceback does not name the
    offending artifact or the remedy, and an unresolved merge conflict in a
    source artifact surfaces as an opaque json decoder error. Name the path,
    detect conflict markers, and point at ``make gen-docs``.
    """
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        rel = path.relative_to(PACKAGE_ROOT) if path.is_relative_to(PACKAGE_ROOT) else path
        raise FileNotFoundError(
            f"missing source artifact: {rel}. Regenerate the artifacts and run "
            "`make gen-docs` (the doc generator reads only committed/force-tracked "
            "source-of-truth artifacts)."
        ) from exc
    if _CONFLICT_MARKER_RE.search(raw):
        rel = path.relative_to(PACKAGE_ROOT) if path.is_relative_to(PACKAGE_ROOT) else path
        raise ValueError(
            f"unresolved merge conflict in {rel}: it contains git conflict markers "
            "(<<<<<<< / ======= / >>>>>>>). Resolve the conflict (or rerun "
            "`make gen-docs` to regenerate it) before generating docs."
        )
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        rel = path.relative_to(PACKAGE_ROOT) if path.is_relative_to(PACKAGE_ROOT) else path
        raise ValueError(
            f"malformed JSON in source artifact {rel} "
            f"(line {exc.lineno}, column {exc.colno}): {exc.msg}. "
            "Regenerate it and run `make gen-docs`."
        ) from exc


class Facts:
    """Parsed reference-variant facts pulled from the artifacts.

    All accessors read ONLY the source-of-truth artifacts named in the
    architecture; nothing is hand-typed.
    """

    def __init__(self) -> None:
        self.summary = _load_json(RESEARCH_SUMMARY_PATH)
        self.load_metadata = _load_json(LOAD_METADATA_PATH)
        self.split_metadata = _load_json(SPLIT_METADATA_PATH)
        self.first_item = _load_json(FIRST_ITEM_PATH)
        self.tuned_params = _load_json(TUNED_PARAMS_PATH)
        self.norms_artifact = _load_json(NORMS_PATH)

        self.rni: dict[str, Any] = self.summary["reference_notes_inputs"]
        self.reference: dict[str, Any] = self.summary["variants"]["reference"]

        # ml_vs_averaging comparisons indexed by (method, n_items).
        self._mva: dict[tuple[str, int], dict[str, Any]] = {
            (row["method"], row["n_items"]): row
            for row in self.rni["ml_vs_averaging_comparison"]["comparisons"]
        }

        self._assert_deployed_coverage_consistent()

    # Genuine semantic tolerance between the two 'deployed 20-item form' coverage
    # operating points (~1 pct point). They are *distinct* operating points, so
    # exact .1f%-display equality is too tight: today they are 89.52% vs 89.47%
    # and round equal only by landing in the same display bucket. A retrain that
    # nudges either across a rounding boundary must not hard-fail all doc
    # generation when each number is individually correct -- only a real
    # divergence (~1 pct point) should.
    _DEPLOYED_COVERAGE_TOL = 0.01

    def _assert_deployed_coverage_consistent(self) -> None:
        """Fail loudly if the two 'deployed 20-item form' coverage sources diverge.

        ``comparison-table`` labels the fixed-mask K=20 domain-balanced baseline
        (``baselines.k20.domain_balanced.coverage_90``) as the deployed form,
        while ``coverage-by-regime`` labels the SEM-stopped adaptive simulation
        (``simulation_results.analysis.overall_metrics.coverage_90``) as the same
        deployed form. They are semantically distinct operating points but both
        carry the "deployed 20-item form" prose. There is no shared constant
        tying them together, so a refresh could make them genuinely disagree
        while both prose blocks still claim the deployed form. Assert they agree
        to a real semantic tolerance (``_DEPLOYED_COVERAGE_TOL``, ~1 pct point)
        -- NOT exact .1f%-display equality, which a benign post-retrain rounding
        straddle could trip even though each number is individually correct.
        """
        fixed = float(self.reference["baselines"]["k20"]["domain_balanced"]["coverage_90"])
        adaptive = float(
            self.rni["simulation_results"]["analysis"]["overall_metrics"]["coverage_90"]
        )
        if abs(fixed - adaptive) >= self._DEPLOYED_COVERAGE_TOL:
            raise ValueError(
                "'deployed 20-item form' coverage diverges beyond the semantic "
                f"tolerance ({self._DEPLOYED_COVERAGE_TOL * 100:.1f} pct points) "
                f"between baselines.k20.domain_balanced ({fixed:.4f} -> "
                f"{fixed * 100:.1f}%) and simulation_results overall_metrics "
                f"({adaptive:.4f} -> {adaptive * 100:.1f}%); comparison-table and "
                "coverage-by-regime both label this the deployed form. Reconcile "
                "the artifacts or relabel one regime before regenerating docs."
            )

    def mva(self, method: str, n_items: int) -> dict[str, Any]:
        return self._mva[(method, n_items)]

    # -- data counts ------------------------------------------------------- #
    @property
    def n_valid(self) -> int:
        n_valid = int(self.load_metadata["row_counts"]["n_valid"])
        # Cross-check against split_metadata.total_valid so a desync fails loudly.
        if n_valid != int(self.split_metadata["total_valid"]):
            raise ValueError(
                "load_metadata.n_valid != split_metadata.total_valid: "
                f"{n_valid} != {self.split_metadata['total_valid']}"
            )
        return n_valid

    @property
    def train_rows(self) -> int:
        return int(self.split_metadata["train_rows"])

    @property
    def val_rows(self) -> int:
        return int(self.split_metadata["val_rows"])

    @property
    def test_rows(self) -> int:
        return int(self.split_metadata["test_rows"])

    @property
    def split_scheme(self) -> str:
        return str(self.split_metadata["split_scheme"])

    @property
    def split_id(self) -> str:
        return str(self.split_metadata["split_id"])

    @property
    def seed(self) -> int:
        return int(self.split_metadata["seed"])

    @property
    def train_frac(self) -> float:
        return float(self.split_metadata["train_frac"])

    @property
    def val_frac(self) -> float:
        return float(self.split_metadata["val_frac"])

    @property
    def test_frac(self) -> float:
        return float(self.split_metadata["test_frac"])

    # -- first item -------------------------------------------------------- #
    @property
    def first_item_selected(self) -> dict[str, Any]:
        return self.first_item["selected_item"]


# --------------------------------------------------------------------------- #
# repo-facts.generated.ts  (MECHANISM 1)
# --------------------------------------------------------------------------- #
def _num(value: float, places: int) -> float:
    """Round to ``places`` decimals, mirroring the committed repoFacts display."""
    return round(float(value), places)


def build_repo_facts(facts: Facts) -> dict[str, Any]:
    """Assemble the reference-variant repoFacts object from artifacts."""
    ref = facts.reference
    rni = facts.rni
    sim = ref["simulation"]
    norms = rni["norms"]["norms"]
    rbar = rni["reliability"]["full_50"]
    db20 = facts.mva("domain_balanced", 20)
    mi20 = facts.mva("mini_ipip", 20)
    selected = facts.first_item_selected

    # Cross-check that every domain shares the same mean_items_used before
    # presenting it as a single global per-domain mean (and 5x-ing it for the
    # total). Mirrors the n_valid / augmentation-counts cross-checks so an
    # unequal future simulation fails loudly instead of silently using 'ext'.
    per_domain_items = [
        float(sim["domain_metrics"][dom]["mean_items_used"]) for dom in DOMAIN_ORDER
    ]
    mean_items_per_domain = per_domain_items[0]
    if any(v != mean_items_per_domain for v in per_domain_items):
        raise ValueError(
            "simulation mean_items_used differs across domains "
            f"(per-domain {dict(zip(DOMAIN_ORDER, per_domain_items, strict=True))}); "
            "meanItemsPerDomain assumes one shared global mean"
        )

    # K=20 unconstrained greedy adaptive_topk per-domain item allocation: the
    # exact correlation-ranking result that produces domain starvation (ch10's
    # greedy-failure barList). Sourced so it can never silently desync on a re-run.
    greedy_topk20 = rni["baseline_comparison_results"]["per_domain"]["20"]["adaptive_topk"]

    return {
        "totalValidRespondents": facts.n_valid,
        "trainRows": facts.train_rows,
        "valRows": facts.val_rows,
        "testRows": facts.test_rows,
        "firstItemId": str(selected["id"]),
        "firstItemText": str(selected["text"]),
        "firstItemCrossDomainInfo": _num(selected["cross_domain_info"], 4),
        "splitScheme": facts.split_scheme,
        "baselineK20": {
            "domainBalancedR": _num(ref["baselines"]["k20"]["domain_balanced"]["pearson_r"], 4),
            "domainBalancedMae": _num(ref["baselines"]["k20"]["domain_balanced"]["mae"], 2),
            "miniIpipStandaloneR": _num(ref["baselines"]["k20"]["mini_ipip"]["pearson_r"], 4),
            "adaptiveTopKR": _num(ref["baselines"]["k20"]["adaptive_topk"]["pearson_r"], 4),
            "constrainedAdaptiveR": _num(
                ref["baselines"]["k20"]["domain_constrained_adaptive"]["pearson_r"], 4
            ),
        },
        "mlVsAveragingK20": {
            "domainBalanced": {
                "mlR": _num(db20["ml_r"], 4),
                "avgR": _num(db20["avg_r"], 4),
                "deltaR": _num(db20["delta_r"], 4),
            },
            "miniIpip": {
                "mlR": _num(mi20["ml_r"], 4),
                "avgR": _num(mi20["avg_r"], 4),
                "deltaR": _num(mi20["delta_r"], 4),
            },
        },
        "validation": {
            "full50R": _num(ref["validation"]["full_50"]["pearson_r"], 4),
            "full50Mae": _num(ref["validation"]["full_50"]["mae"], 2),
            "full50Coverage": _num(ref["validation"]["full_50"]["coverage_90"], 4),
            "sparse20R": _num(ref["validation"]["sparse_20"]["pearson_r"], 4),
            "sparse20Mae": _num(ref["validation"]["sparse_20"]["mae"], 2),
            "sparse20Coverage": _num(ref["validation"]["sparse_20"]["coverage_90"], 4),
        },
        "simulation": {
            "overallR": _num(sim["overall"]["pearson_r"], 4),
            "overallMae": _num(sim["overall"]["mae"], 2),
            "overallCoverage": _num(sim["overall"]["coverage_90"], 4),
            "meanItemsPerDomain": _int_or_float(mean_items_per_domain),
            "meanItemsTotal": _int_or_float(5 * mean_items_per_domain),
        },
        "norms": {
            dom: {
                "mean": _num(norms[dom]["mean"], 4),
                "sd": _num(norms[dom]["sd"], 4),
            }
            for dom in DOMAIN_ORDER
        },
        "interItemRBar": {dom: _num(rbar[dom]["r_bar"], 4) for dom in DOMAIN_ORDER},
        "greedyTopK20ItemsPerDomain": {
            dom: int(greedy_topk20[dom]["n_domain_items"]) for dom in DOMAIN_ORDER
        },
        "currentLockedParams": dict(facts.tuned_params["hyperparameters"]),
    }


def _int_or_float(value: float) -> int | float:
    """Render whole numbers as ints (4.0 -> 4) so they round-trip cleanly."""
    fvalue = float(value)
    return int(fvalue) if fvalue.is_integer() else fvalue


def _ts_value(value: Any, indent: int) -> str:
    pad = "  " * indent
    inner = "  " * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = ["{"]
        for key, val in value.items():
            lines.append(f"{inner}{_ts_key(key)}: {_ts_value(val, indent + 1)},")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        # repr keeps the full float precision (e.g. learning_rate) and emits a
        # decimal point so TS sees a number literal.
        return repr(value)
    raise TypeError(f"unsupported repoFacts value type: {type(value)!r}")


_TS_IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _ts_key(key: str) -> str:
    return key if _TS_IDENT.match(key) else json.dumps(key)


def render_repo_facts_ts(facts: Facts) -> str:
    obj = build_repo_facts(facts)
    body = _ts_value(obj, 0)
    return f"{GENERATED_HEADER}\nexport const repoFacts = {body} as const;\n"


# --------------------------------------------------------------------------- #
# Markdown render functions (MECHANISM 2)
# --------------------------------------------------------------------------- #
def _fmt_r3(value: float) -> str:
    """Pearson r in leading-dot 3-decimal style (0.928 -> '.928', -0.05 -> '-.050').

    Strip only the leading zero of the magnitude, preserving any sign. A plain
    ``lstrip("0")`` is a no-op on a negative value (the string starts with '-'),
    rendering '-0.050' next to leading-dot '.928' siblings -- an inconsistency a
    sub-zero ablation correlation would surface in the comparison/per-domain
    tables. ``re.sub`` collapses both the positive and negative cases uniformly
    and never widens the cell.
    """
    return re.sub(r"^(-?)0\.", r"\1.", f"{value:.3f}")


def _cell(content: str, inner_width: int) -> str:
    """Render a Markdown cell body ' content...' padded to ``inner_width`` chars.

    The committed README tables use fixed (slightly irregular) inner-cell widths;
    reproducing them byte-for-byte keeps the injected diff to numbers only.
    """
    body = f" {content}"
    if len(body) > inner_width:
        raise ValueError(f"cell {content!r} exceeds width {inner_width}")
    return body + " " * (inner_width - len(body))


def render_comparison_table(facts: Facts) -> str:
    """Mini-IPIP (averaging) vs BFFM-XGB-20 (XGBoost) headline table."""
    db20 = facts.mva("domain_balanced", 20)
    mi20 = facts.mva("mini_ipip", 20)
    coverage = facts.reference["baselines"]["k20"]["domain_balanced"]["coverage_90"]

    overall_mini = _fmt_r3(mi20["avg_r"])
    overall_xgb = _fmt_r3(db20["ml_r"])
    mae_mini = f"{mi20['avg_mae']:.1f}"
    mae_xgb = f"{db20['ml_mae']:.1f}"
    cov_pct = f"{coverage * 100:.1f}"

    # Fixed inner-cell widths matching the committed table (col1=30, col2=24, col3=29).
    rows = [
        "|                              | Mini-IPIP (averaging)  | BFFM-XGB-20 (XGBoost)       |",
        "| ---------------------------- | ---------------------- | --------------------------- |",
        "| **Items**                    | 20 (4 per domain)      | 20 (4 per domain)           |",
        "| **Item selection**           | Expert-curated brevity | Top-4 by within-domain *r*  |",
        "| **Scoring**                  | Simple scale averaging | XGBoost quantile regression |",
        f"|{_cell('**Overall *r***', 30)}|{_cell(overall_mini, 24)}|{_cell(f'**{overall_xgb}**', 29)}|",
        f"|{_cell('**MAE (percentile pts)**', 30)}|{_cell(mae_mini, 24)}|{_cell(f'**{mae_xgb}**', 29)}|",
        f"|{_cell('**90% prediction intervals**', 30)}|{_cell('—', 24)}|{_cell(f'✓ ({cov_pct}% coverage)', 29)}|",
    ]
    return "\n".join(rows)


def render_per_domain_k20(facts: Facts) -> str:
    """Per-domain accuracy at K=20: Mini-IPIP averaging r vs BFFM-XGB-20 r.

    The Mini-IPIP *alpha* column is a hand-cited published Donnellan et al.
    (2006) literature constant (NOT artifact-derived); it is carried through
    verbatim so the generated table matches the committed prose.
    """
    db20 = facts.mva("domain_balanced", 20)
    mi20 = facts.mva("mini_ipip", 20)

    # Hand-cited published reliabilities (literature constant, not this sample).
    published_alpha = {
        "ext": ".77",
        "agr": ".70",
        "csn": ".69",
        "est": ".68",
        "opn": ".65",
    }

    header = [
        "| Domain                | Mini-IPIP *α* (reported) | Mini-IPIP *r* (averaging) | BFFM-XGB-20 *r* (XGBoost) |",
        "| --------------------- | ------------------------ | ------------------------- | ------------------------- |",
    ]
    rows: list[str] = []
    # Fixed inner-cell widths matching the committed table (col1=23, col2=26, col3=15, col4=17).
    for dom in DOMAIN_ORDER:
        label = DOMAIN_LABELS[dom]
        alpha = published_alpha[dom]
        mini = _fmt_r3(mi20["avg_per_domain"][dom])
        xgb = _fmt_r3(db20["ml_per_domain"][dom])
        rows.append(
            f"|{_cell(label, 23)}|{_cell(alpha, 26)}|{_cell(mini, 15)}|{_cell(f'**{xgb}**', 17)}|"
        )
    return "\n".join(header + rows)


def render_data_counts(facts: Facts) -> str:
    """Key data counts: raw -> valid -> seed-locked 70/15/15 splits."""
    train_pct = f"{facts.train_frac * 100:.0f}"
    val_pct = f"{facts.val_frac * 100:.0f}"
    test_pct = f"{facts.test_frac * 100:.0f}"
    return "\n".join(
        [
            f"- **Valid respondents:** {facts.n_valid:,} (from {facts.load_metadata['row_counts']['n_raw']:,} raw rows after cleaning)",
            f"- **Split (`{facts.split_id}`, {facts.split_scheme}, seed {facts.seed}):** "
            f"{train_pct}/{val_pct}/{test_pct} = {facts.train_rows:,} train / "
            f"{facts.val_rows:,} val / {facts.test_rows:,} test",
        ]
    )


def render_decomposition(facts: Facts) -> str:
    """Scoring-vs-selection decomposition for the 20-item gain (+ bootstrap CI)."""
    db20 = facts.mva("domain_balanced", 20)
    mi20 = facts.mva("mini_ipip", 20)

    per_domain_deltas = {
        dom: db20["ml_per_domain"][dom] - db20["avg_per_domain"][dom] for dom in DOMAIN_ORDER
    }
    delta_min = min(per_domain_deltas.values())
    delta_max = max(per_domain_deltas.values())
    overall_delta = db20["delta_r"]
    ci_low, ci_high = db20["delta_r_ci"]

    est_mini_beats = mi20["ml_per_domain"]["est"] > db20["ml_per_domain"]["est"]
    est_note = (
        "for Emotional Stability the Mini-IPIP items scored with XGBoost slightly "
        "*beat* the top-4-by-*r* selection (scoring, not selection)"
        if est_mini_beats
        else "every domain's gain combines scoring and selection"
    )

    return "\n".join(
        [
            f"- **Scoring lever (item set held fixed):** XGBoost scoring alone adds "
            f"roughly {delta_min:+.3f} to {delta_max:+.3f} *r* per domain "
            f"over averaging (about {overall_delta:+.3f} overall, "
            f"bootstrap 95% CI [{ci_low:+.4f}, {ci_high:+.4f}]).",
            f"- **Selection lever:** the remainder of the 20-item gain is item "
            f"selection (top-4-by-*r* vs the expert-curated Mini-IPIP items); {est_note}.",
        ]
    )


def render_coverage_by_regime(facts: Facts) -> str:
    """Empirical 90%-PI coverage at each evaluation regime (+ paired r).

    Sourced so the three regimes can never silently desync:
    - deployed 20-item form  -> simulation_results (SEM-stopped adaptive sim),
      which pairs the ~89.5% deployed coverage with its r ~ .93 operating point.
    - random balanced 20-item masking -> validation_results.sparse_20 (~89.8%).
    - full 50 items -> validation_results full-50 self-recovery (~92.6%).
    The interval is the raw tau=0.05/0.95 spread; nominal target is 90%.
    """
    sim = facts.rni["simulation_results"]["analysis"]["overall_metrics"]
    sparse = facts.rni["validation_results"]["sparse_20"]["metrics"]["overall"]
    full = facts.rni["validation_results"]["metrics"]["overall"]
    return "\n".join(
        [
            f"- **Deployed 20-item form (SEM-stopped adaptive sim):** "
            f"{sim['coverage_90'] * 100:.1f}% empirical coverage "
            f"(*r* = {sim['pearson_r']:.2f}) — slightly under the nominal 90% by design.",
            f"- **Random balanced 20-item masking:** "
            f"{sparse['coverage_90'] * 100:.1f}% empirical coverage "
            f"(*r* = {sparse['pearson_r']:.3f}).",
            f"- **Full 50 items (self-recovery):** "
            f"{full['coverage_90'] * 100:.1f}% empirical coverage "
            f"(*r* = {full['pearson_r']:.4f}).",
        ]
    )


def render_training_config(facts: Facts) -> str:
    """Recorded config of the published reference run (tuning + training threads).

    These are recorded properties of the reference bundle, not free constants:
    - n_trials       -> tuned_params.provenance.n_trials (the Optuna budget)
    - cv_folds       -> training_report.config.training.cv_folds
    - xgb_n_jobs     -> training_report.config.xgb_n_jobs (CLI override; the
      thread count needed to reproduce model.onnx byte-for-byte)
    """
    tr = facts.rni["training_report"]
    n_trials = int(facts.tuned_params["provenance"]["n_trials"])
    cv_folds = int(tr["config"]["training"]["cv_folds"])
    xgb_n_jobs = int(tr["config"]["xgb_n_jobs"])
    return "\n".join(
        [
            f"- **Optuna tuning budget:** {n_trials} trials.",
            f"- **Cross-validation:** {cv_folds}-fold.",
            f"- **Recorded XGBoost thread count (published bundle):** "
            f"`xgb_n_jobs = {xgb_n_jobs}` (CLI override) — reproduce byte-for-byte "
            f"with `make train N_JOBS={xgb_n_jobs}`.",
        ]
    )


def render_augmentation_counts(facts: Facts) -> str:
    """Sparsity-augmentation row accounting (reference-config-derived).

    Every count is derived from the published reference training_report so the
    docs cannot desync from the run:
      - ``train_rows`` (canonical split) and ``train_rows_after_augmentation``
        are recorded directly;
      - ``fit_rows`` = augmented / n_augmentation_passes (the fit respondents
        that are actually tripled);
      - ``early_stop_holdout_rows`` = train_rows - fit_rows (carved out of the
        train split *before* augmentation, so it is never masked).
    """
    tr = facts.rni["training_report"]
    passes = int(tr["config"]["sparsity"]["n_augmentation_passes"])
    train_rows = int(tr["data"]["train_rows"])
    augmented = int(tr["data"]["train_rows_after_augmentation"])
    if augmented % passes != 0:
        raise ValueError(
            f"train_rows_after_augmentation ({augmented}) not divisible by "
            f"n_augmentation_passes ({passes})"
        )
    fit_rows = augmented // passes
    early_stop_rows = train_rows - fit_rows
    return "\n".join(
        [
            f"- **Training rows (canonical split):** {train_rows:,}",
            f"- **Early-stopping hold-out (split off *before* augmentation):** "
            f"{early_stop_rows:,} rows",
            f"- **Fit respondents (the rows that get augmented):** {fit_rows:,}",
            f"- **Augmentation passes:** {passes} (each fit respondent re-masked {passes}×)",
            f"- **Augmented training rows:** {fit_rows:,} × {passes} = {augmented:,}",
        ]
    )


def render_norms_table(facts: Facts) -> str:
    """Per-domain training-split norms (mean / SD) for percentile conversion.

    Sourced from research_summary ``reference_notes_inputs.norms.norms`` (mirror
    of ``artifacts/ipip_bffm_norms.json``); these are the z-score reference
    statistics, displayed to four decimals to match the web norms table.
    """
    norms = facts.rni["norms"]["norms"]
    header = [
        "| Domain                | Mean   | SD     |",
        "| --------------------- | ------ | ------ |",
    ]
    rows: list[str] = []
    for dom in DOMAIN_ORDER:
        label = DOMAIN_LABELS[dom]
        mean = f"{norms[dom]['mean']:.4f}"
        sd = f"{norms[dom]['sd']:.4f}"
        rows.append(f"|{_cell(label, 23)}|{_cell(mean, 8)}|{_cell(sd, 8)}|")
    return "\n".join(header + rows)


# Pedagogical fixed raw score for the norms worked example (design constant;
# mirrors web ch03 ``EXAMPLE_RAW_SCORE``). The mean/SD/z/percentile are all
# derived from the artifact norms below, never hand-typed.
NORMS_EXAMPLE_RAW_SCORE = 3.80


def render_norms_worked_example(facts: Facts) -> str:
    """Worked z-score -> percentile example for one domain (Extraversion).

    Mean and SD come from the artifact norms; z and the normal-CDF percentile
    are computed here, so the prose can never drift from the table above. The
    only inline constant is the pedagogical raw score (3.80), matching the web
    ch03 worked example exactly (z ~ 0.972, percentile ~ 83.4).
    """
    ext = facts.rni["norms"]["norms"]["ext"]
    mean = float(ext["mean"])
    sd = float(ext["sd"])
    x = NORMS_EXAMPLE_RAW_SCORE
    z = (x - mean) / sd
    percentile = 0.5 * (1.0 + math.erf(z / math.sqrt(2.0))) * 100.0
    return (
        f"An Extraversion raw score of {x:.2f} maps to "
        f"*z* = ({x:.2f} − {mean:.4f}) / {sd:.4f} ≈ {z:.3f}, i.e. about the "
        f"{percentile:.1f}th percentile of the reference sample."
    )


RENDERERS: dict[str, Callable[[Facts], str]] = {
    "comparison-table": render_comparison_table,
    "per-domain-k20": render_per_domain_k20,
    "data-counts": render_data_counts,
    "decomposition": render_decomposition,
    "coverage-by-regime": render_coverage_by_regime,
    "training-config": render_training_config,
    "augmentation-counts": render_augmentation_counts,
    "norms-table": render_norms_table,
    "norms-worked-example": render_norms_worked_example,
}

GENERATED_KEYS = sorted(RENDERERS.keys())


# --------------------------------------------------------------------------- #
# Marker injection
# --------------------------------------------------------------------------- #
_FENCE_RE = re.compile(
    # The ``\n?`` before END keeps populated fences byte-for-byte identical (it
    # greedily eats the separating newline) while also matching a *tight* empty
    # fence (``BEGIN -->\n<!-- END -->``) so a brand-new, not-yet-populated fence
    # still injects instead of being silently skipped.
    r"(?P<begin><!-- BEGIN GENERATED: (?P<key>[a-z0-9-]+) -->\n)"
    r"(?P<body>.*?)"
    r"(?P<end>\n?<!-- END GENERATED: (?P=key) -->)",
    re.DOTALL,
)

# Any literal GENERATED marker text. After a successful inject pass NONE of these
# should survive un-consumed: a residual marker means a malformed fence (tight-?
# only handled above, but also unterminated, mismatched BEGIN/END keys, or a key
# the [a-z0-9-]+ class can't capture, e.g. uppercase) slipped past _FENCE_RE.
_MARKER_RE = re.compile(r"<!-- (BEGIN|END) GENERATED:")


def inject_markdown(text: str, facts: Facts, source: Path) -> str:
    """Replace the inner body of each GENERATED fence with its rendered block.

    Defensive: any GENERATED marker that survives the substitution (because the
    surrounding fence was malformed -- unterminated, mismatched BEGIN/END keys,
    an un-capturable key like uppercase, etc.) raises ValueError. Without this a
    broken fence is a silent no-op and ``--check`` reports 'ok', so an author who
    mistypes a fence gets stale/placeholder content forever with no CI failure.
    """

    def _replace(match: re.Match[str]) -> str:
        key = match.group("key")
        renderer = RENDERERS.get(key)
        if renderer is None:
            raise KeyError(
                f"{source.name}: unknown GENERATED key {key!r}; "
                f"known keys: {', '.join(GENERATED_KEYS)}"
            )
        rendered = renderer(facts).rstrip("\n")
        return f"{match.group('begin')}{rendered}{match.group('end')}"

    injected = _FENCE_RE.sub(_replace, text)

    # Well-formed fences legitimately still contain their BEGIN/END markers after
    # substitution, so strip every well-formed fence first; any GENERATED marker
    # left over belongs to a malformed fence that _FENCE_RE could not match.
    residual = _MARKER_RE.findall(_FENCE_RE.sub("", injected))
    if residual:
        raise ValueError(
            f"{source.name}: {len(residual)} malformed GENERATED marker(s) survived "
            "injection (unterminated fence, mismatched BEGIN/END keys, or an "
            "uncapturable key such as uppercase). Every fence must be "
            "'<!-- BEGIN GENERATED: <key> -->' ... '<!-- END GENERATED: <key> -->' "
            f"with a lowercase key in: {', '.join(GENERATED_KEYS)}."
        )
    return injected


# --------------------------------------------------------------------------- #
# Modes
# --------------------------------------------------------------------------- #
def run_repo_facts(facts: Facts, check: bool) -> bool:
    """Write (or check) repo-facts.generated.ts. Returns True on success."""
    new_content = render_repo_facts_ts(facts)
    if check:
        if not REPO_FACTS_OUT.exists():
            print(f"MISSING: {REPO_FACTS_OUT.relative_to(PACKAGE_ROOT)}", file=sys.stderr)
            return False
        current = REPO_FACTS_OUT.read_text(encoding="utf-8")
        if current != new_content:
            print(
                f"STALE: {REPO_FACTS_OUT.relative_to(PACKAGE_ROOT)} "
                "is out of date; run `make gen-docs`.",
                file=sys.stderr,
            )
            return False
        print(f"ok: {REPO_FACTS_OUT.relative_to(PACKAGE_ROOT)}")
        return True
    REPO_FACTS_OUT.write_text(new_content, encoding="utf-8")
    print(f"wrote {REPO_FACTS_OUT.relative_to(PACKAGE_ROOT)}")
    return True


def run_inject(facts: Facts, check: bool) -> bool:
    """Inject (or check) GENERATED fences in the markdown targets."""
    ok = True
    for path in MARKDOWN_TARGETS:
        if not path.exists():
            continue
        current = path.read_text(encoding="utf-8")
        if "<!-- BEGIN GENERATED:" not in current:
            continue
        updated = inject_markdown(current, facts, path)
        if check:
            if updated != current:
                print(
                    f"STALE: {path.relative_to(PACKAGE_ROOT)} "
                    "has out-of-date generated blocks; run `make gen-docs`.",
                    file=sys.stderr,
                )
                ok = False
            else:
                print(f"ok: {path.relative_to(PACKAGE_ROOT)}")
        elif updated != current:
            path.write_text(updated, encoding="utf-8")
            print(f"injected {path.relative_to(PACKAGE_ROOT)}")
        else:
            print(f"unchanged {path.relative_to(PACKAGE_ROOT)}")
    return ok


def list_markdown_targets() -> list[str]:
    """Repo-relative paths of every markdown file the generator injects.

    The single source of truth for the injected-file set so the Makefile's
    check-docs git-diff guard can derive its list from here (via the
    ``list-targets`` mode) instead of hand-duplicating MARKDOWN_TARGETS, which
    would silently un-guard a file if the two lists ever drift apart.
    """
    return [str(path.relative_to(PACKAGE_ROOT)) for path in MARKDOWN_TARGETS]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "mode",
        choices=["repo-facts", "inject", "all", "list-targets"],
        help=(
            "repo-facts: emit the .ts; inject: rewrite markdown fences; "
            "all: both; list-targets: print the injected .md paths (for the "
            "check-docs git-diff guard) and exit"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify outputs are up to date without writing (non-zero exit if stale)",
    )
    args = parser.parse_args(argv)

    if args.mode == "list-targets":
        for target in list_markdown_targets():
            print(target)
        return 0

    facts = Facts()
    ok = True
    if args.mode in ("repo-facts", "all"):
        ok = run_repo_facts(facts, args.check) and ok
    if args.mode in ("inject", "all"):
        ok = run_inject(facts, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
