#!/usr/bin/env python3
"""Generate notes/NOTES.md from templates/NOTES.md and pipeline artifacts.

Reads the template from templates/NOTES.md, fills data sections between
<!-- BEGIN:name --> / <!-- END:name --> markers with pipeline-derived tables,
and writes the result to notes/NOTES.md. The template contains only
hand-authored narrative; all data sections are populated at generation time.

Usage:
    python scripts/generate_notes_data.py            # generate notes/NOTES.md
    python scripts/generate_notes_data.py --dry-run  # print sections without writing
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = PACKAGE_ROOT / "artifacts"
CONFIGS_DIR = PACKAGE_ROOT / "configs"
NOTES_TEMPLATE_PATH = PACKAGE_ROOT / "templates" / "NOTES.md"
NOTES_PATH = PACKAGE_ROOT / "notes" / "NOTES.md"
RESEARCH_SUMMARY_PATH = ARTIFACTS_DIR / "research_summary.json"

DOMAIN_ORDER = ["ext", "agr", "csn", "est", "opn"]
DOMAIN_LABELS = {
    "ext": "Extraversion",
    "agr": "Agreeableness",
    "csn": "Conscientiousness",
    "est": "Emotional Stability",
    "opn": "Intellect/Openness",
}
DOMAIN_KEYS_BASELINE = {
    "ext": "Extraversion",
    "agr": "Agreeableness",
    "csn": "Conscientiousness",
    "est": "EmotionalStability",
    "opn": "Intellect",
}
VARIANT_ORDER = [
    "reference",
    "ablation_none",
    "ablation_focused",
    "ablation_stratified",
]
VARIANT_LABELS = {
    "reference": "Reference",
    "ablation_none": "Ablation: No Sparsity",
    "ablation_focused": "Ablation: Focused Only",
    "ablation_stratified": "Ablation: Stratified Split",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def load_yaml(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def load_research_summary() -> dict:
    """Load cross-variant summary generated by scripts/build_research_summary.py."""
    if not RESEARCH_SUMMARY_PATH.exists():
        raise FileNotFoundError(
            f"Missing {RESEARCH_SUMMARY_PATH}. Run `make research-summary` first."
        )
    payload = load_json(RESEARCH_SUMMARY_PATH)
    variants = payload.get("variants")
    if not isinstance(variants, dict):
        raise ValueError(
            f"{RESEARCH_SUMMARY_PATH} is missing required 'variants' object."
        )
    return payload


def load_reference_notes_inputs() -> dict:
    """Load canonical reference inputs from research_summary.json."""
    payload = load_research_summary()
    notes_inputs = payload.get("reference_notes_inputs")
    if not isinstance(notes_inputs, dict):
        raise ValueError(
            f"{RESEARCH_SUMMARY_PATH} is missing required 'reference_notes_inputs' object."
        )
    return notes_inputs


def load_variant_notes_inputs(variant: str) -> dict:
    """Load variant-scoped NOTES inputs from research_summary.json."""
    payload = load_research_summary()
    variants = payload.get("variants", {})
    if not isinstance(variants, dict):
        raise ValueError(f"{RESEARCH_SUMMARY_PATH} has invalid 'variants' object.")
    variant_payload = variants.get(variant)
    if not isinstance(variant_payload, dict):
        raise KeyError(f"research_summary variant '{variant}' missing.")
    notes_inputs = variant_payload.get("notes_inputs")
    if not isinstance(notes_inputs, dict):
        raise KeyError(
            f"research_summary variant '{variant}' is missing required 'notes_inputs'."
        )
    return notes_inputs


def _notes_input_dict(notes_inputs: dict, key: str) -> dict:
    value = notes_inputs.get(key)
    if isinstance(value, dict):
        err = value.get("__error__")
        if isinstance(err, str):
            raise ValueError(f"research_summary reference input '{key}' error: {err}")
        return value
    raise KeyError(f"research_summary reference input '{key}' missing or invalid.")


def _notes_input_rows(notes_inputs: dict, key: str) -> list[dict]:
    value = notes_inputs.get(key)
    if isinstance(value, list):
        return [row for row in value if isinstance(row, dict)]
    raise KeyError(f"research_summary reference input '{key}' missing or invalid.")


def _resolve_calibration_policy_fields(policy: dict) -> tuple[str, str, str]:
    """Normalize calibration policy keys across artifact schema revisions."""
    full_50 = policy.get("n_items_50_or_more")
    sparse = policy.get("n_items_below_50", policy.get("n_items_20"))
    fallback = policy.get(
        "fallback_without_sparse_calibration",
        policy.get("other_n_items"),
    )
    if not isinstance(full_50, str) or not isinstance(sparse, str) or not isinstance(fallback, str):
        raise KeyError(
            "baseline_comparison_results.json config.calibration_policy is missing required keys."
        )
    return full_50, sparse, fallback


def load_hyperparameters_for_notes() -> dict:
    """Load hyperparameters from canonical research summary notes inputs."""
    notes_inputs = load_reference_notes_inputs()
    tuned = _notes_input_dict(notes_inputs, "tuned_params")
    hp = tuned.get("hyperparameters")
    if isinstance(hp, dict) and hp:
        return hp
    raise KeyError("research_summary reference input 'tuned_params.hyperparameters' missing.")


def fmt_r(val: float, places: int = 4) -> str:
    """Format a correlation value with fixed decimal places."""
    return f"{val:.{places}f}"


def fmt_r3(val: float) -> str:
    return fmt_r(val, 3)


def fmt_pct(val: float) -> str:
    return f"{val:.1f}%"


def fmt_f(val: float, places: int = 2) -> str:
    return f"{val:.{places}f}"


def fmt_opt_float(val: Any, places: int = 4) -> str:
    if isinstance(val, (int, float)):
        return fmt_f(float(val), places)
    return "---"


def _get_nested(d: dict, keys: list[str]) -> Any:
    curr: Any = d
    for key in keys:
        if not isinstance(curr, dict):
            return None
        curr = curr.get(key)
    return curr


def pad_table(rows: list[list[str]]) -> str:
    """Render a list-of-lists as a well-spaced markdown table."""
    n_cols = len(rows[0])
    widths = [max(len(str(row[i])) for row in rows) for i in range(n_cols)]
    lines = []
    for idx, row in enumerate(rows):
        cells = [" " + str(row[i]).ljust(widths[i]) + " " for i in range(n_cols)]
        lines.append("|" + "|".join(cells) + "|")
        if idx == 0:
            sep = ["-" * (widths[i] + 2) for i in range(n_cols)]
            lines.append("|" + "|".join(sep) + "|")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------


def gen_model_config() -> str:
    hp = load_hyperparameters_for_notes()
    rows = [
        ["Parameter", "Value"],
        ["Algorithm", "XGBoost quantile regression (pinball loss)"],
        ["Models", "15 (5 domains x 3 quantiles: q05, q50, q95)"],
        ["n_estimators", f"{hp['n_estimators']:,}"],
        ["max_depth", str(hp["max_depth"])],
        ["learning_rate", fmt_f(hp["learning_rate"], 4)],
        ["min_child_weight", str(hp["min_child_weight"])],
        ["subsample", fmt_f(hp["subsample"], 3)],
        ["colsample_bytree", fmt_f(hp["colsample_bytree"], 3)],
        ["reg_lambda", fmt_f(hp["reg_lambda"], 3)],
        ["reg_alpha", fmt_f(hp["reg_alpha"], 3)],
        ["RNG seed", "42"],
    ]
    return pad_table(rows)


def gen_norms() -> str:
    notes_inputs = load_reference_notes_inputs()
    norms_payload = _notes_input_dict(notes_inputs, "norms")
    norms = norms_payload.get("norms")
    if not isinstance(norms, dict):
        raise KeyError("research_summary reference input 'norms.norms' missing.")
    rows = [["Domain", "Mean", "SD"]]
    for d in DOMAIN_ORDER:
        rows.append(
            [DOMAIN_LABELS[d], fmt_f(norms[d]["mean"], 4), fmt_f(norms[d]["sd"], 4)]
        )
    return pad_table(rows)


def gen_validation() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_validation_from_notes_inputs(notes_inputs)


def _gen_validation_from_notes_inputs(notes_inputs: dict) -> str:
    val = _notes_input_dict(notes_inputs, "validation_results")
    metrics = val["metrics"]
    rows = [
        ["Domain", "r", "MAE", "RMSE", "Within-5", "90% Coverage", "Raw Crossing Rate"]
    ]
    for d in DOMAIN_ORDER:
        dm = metrics[d]
        rows.append(
            [
                DOMAIN_LABELS[d],
                fmt_f(dm["pearson_r"], 4),
                fmt_f(dm["mae"], 2),
                fmt_f(dm["rmse"], 2),
                fmt_pct(dm["within_5_pct"] * 100),
                fmt_pct(dm["coverage_90"] * 100),
                fmt_pct(
                    dm.get("raw_crossing_rate", dm.get("quantile_crossing_rate", 0))
                    * 100
                ),
            ]
        )
    ov = metrics["overall"]
    rows.append(
        [
            "**Overall**",
            f"**{fmt_f(ov['pearson_r'], 4)}**",
            f"**{fmt_f(ov['mae'], 2)}**",
            f"**{fmt_f(ov['rmse'], 2)}**",
            f"**{fmt_pct(ov['within_5_pct'] * 100)}**",
            "---",
            "---",
        ]
    )
    return pad_table(rows)


def gen_baselines() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_baselines_from_notes_inputs(notes_inputs)


def _gen_baselines_from_notes_inputs(notes_inputs: dict) -> str:
    bl = _notes_input_dict(notes_inputs, "baseline_comparison_results")
    overall = bl[
        "overall"
    ]  # nested: overall[str(k)][method] -> {pearson_r, pearson_r_ci, ...}

    strategy_order = [
        ("domain_balanced", "Domain-Balanced"),
        ("domain_constrained_adaptive", "Constrained-Adaptive"),
        ("mini_ipip", "Mini-IPIP"),
        ("first_n", "First-N"),
        ("random", "Random"),
        ("adaptive_topk", "Adaptive Top-K"),
        ("greedy_balanced", "Greedy-Balanced"),
        ("worst_k", "Worst-K"),
    ]
    rows = [["K"] + [label for _, label in strategy_order]]
    for k in [5, 10, 15, 20, 25, 30, 40, 50]:
        k_data = overall.get(str(k), {})
        row = [str(k)]
        for method, _ in strategy_order:
            entry = k_data.get(method)
            if entry is None:
                row.append("---")
                continue
            r = entry["pearson_r"]
            ci = entry.get("pearson_r_ci")
            r_str = fmt_r3(r)
            if ci:
                r_str += f" [{fmt_r3(ci[0])}, {fmt_r3(ci[1])}]"
            if k == 20 and method in ("domain_balanced", "mini_ipip"):
                r_str = f"**{r_str}**"
            row.append(r_str)
        rows.append(row)
    return pad_table(rows)


def gen_per_domain_k20() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_per_domain_k20_from_notes_inputs(notes_inputs)


def _gen_per_domain_k20_from_notes_inputs(notes_inputs: dict) -> str:
    csv_rows = _notes_input_rows(notes_inputs, "baseline_comparison_per_domain_rows")

    def build_table(method_name: str, label: str) -> str:
        heading = f"**{label}:**\n\n"
        rows = [["Domain", "r", "Items", "CI Lower", "CI Upper"]]
        for csv_row in csv_rows:
            if int(csv_row["n_items"]) != 20 or csv_row["method"] != method_name:
                continue
            for d in DOMAIN_ORDER:
                dk = DOMAIN_KEYS_BASELINE[d]
                r_val = float(csv_row[f"r_{dk}"])
                items = int(float(csv_row[f"items_{dk}"]))
                ci_lo_key = f"r_{dk}_ci_lower"
                ci_hi_key = f"r_{dk}_ci_upper"
                ci_lo = (
                    fmt_r(float(csv_row[ci_lo_key]), 4)
                    if csv_row.get(ci_lo_key)
                    else "---"
                )
                ci_hi = (
                    fmt_r(float(csv_row[ci_hi_key]), 4)
                    if csv_row.get(ci_hi_key)
                    else "---"
                )
                rows.append(
                    [DOMAIN_LABELS[d], fmt_r(r_val, 4), str(items), ci_lo, ci_hi]
                )
            break
        return heading + pad_table(rows)

    parts = [
        build_table("domain_balanced", "Domain-Balanced (4 items per domain)"),
        build_table("mini_ipip", "Mini-IPIP (4 items per domain)"),
        build_table("first_n", "First-N (4 items per domain)"),
    ]
    return "\n\n".join(parts)


def gen_domain_starvation() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_domain_starvation_from_notes_inputs(notes_inputs)


def _gen_domain_starvation_from_notes_inputs(notes_inputs: dict) -> str:
    csv_rows = _notes_input_rows(notes_inputs, "baseline_comparison_per_domain_rows")
    rows = [["Domain", "Items", "Share", "r", "CI Lower", "CI Upper"]]
    for csv_row in csv_rows:
        if int(csv_row["n_items"]) != 20 or csv_row["method"] != "adaptive_topk":
            continue
        # Sort domains by item count descending for starvation visualization
        domain_data = []
        for d in DOMAIN_ORDER:
            dk = DOMAIN_KEYS_BASELINE[d]
            items = int(float(csv_row[f"items_{dk}"]))
            r_val = float(csv_row[f"r_{dk}"])
            ci_lo = (
                float(csv_row[f"r_{dk}_ci_lower"])
                if csv_row.get(f"r_{dk}_ci_lower")
                else None
            )
            ci_hi = (
                float(csv_row[f"r_{dk}_ci_upper"])
                if csv_row.get(f"r_{dk}_ci_upper")
                else None
            )
            domain_data.append((d, items, r_val, ci_lo, ci_hi))
        domain_data.sort(key=lambda x: -x[1])
        for d, items, r_val, ci_lo, ci_hi in domain_data:
            share = f"{items * 100 // 20}%"
            rows.append(
                [
                    DOMAIN_LABELS[d],
                    str(items),
                    share,
                    fmt_r(r_val, 4),
                    fmt_r(ci_lo, 4) if ci_lo else "---",
                    fmt_r(ci_hi, 4) if ci_hi else "---",
                ]
            )
        break
    return pad_table(rows)


def gen_ml_vs_averaging() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_ml_vs_averaging_from_notes_inputs(notes_inputs)


def _gen_ml_vs_averaging_from_notes_inputs(notes_inputs: dict) -> str:
    comp = _notes_input_dict(notes_inputs, "ml_vs_averaging_comparison")
    rows = [
        ["Strategy", "K", "ML r", "Avg r", "Delta r", "ML MAE", "Avg MAE", "Delta MAE"]
    ]
    for entry in comp["comparisons"]:
        method = entry["method"]
        if "domain" in method:
            label = "Domain-balanced"
        elif "mini" in method:
            label = "Mini-IPIP"
        else:
            label = method.replace("_", " ").title()
        rows.append(
            [
                label,
                str(entry["n_items"]),
                fmt_f(entry["ml_r"], 4),
                fmt_f(entry["avg_r"], 4),
                f"{entry['delta_r']:+.4f}",
                fmt_f(entry["ml_mae"], 2),
                fmt_f(entry["avg_mae"], 2),
                f"{entry['delta_mae']:+.2f}",
            ]
        )
    return pad_table(rows)


def gen_simulation() -> str:
    notes_inputs = load_reference_notes_inputs()
    return _gen_simulation_from_notes_inputs(notes_inputs)


def _gen_simulation_from_notes_inputs(notes_inputs: dict) -> str:
    sim = _notes_input_dict(notes_inputs, "simulation_results")
    analysis = sim["analysis"]
    per_domain = analysis["domain_metrics"]
    rows = [["Domain", "r", "MAE", "RMSE", "Within-5", "90% Coverage"]]
    for d in DOMAIN_ORDER:
        dm = per_domain[d]
        rows.append(
            [
                DOMAIN_LABELS[d],
                fmt_f(dm["pearson_r"], 4),
                fmt_f(dm["mae"], 2),
                fmt_f(dm["rmse"], 2),
                fmt_pct(dm["within_5_pct"] * 100),
                fmt_pct(dm["coverage_90"] * 100),
            ]
        )
    ov = analysis["overall_metrics"]
    rows.append(
        [
            "**Overall**",
            f"**{fmt_f(ov['pearson_r'], 4)}**",
            f"**{fmt_f(ov['mae'], 2)}**",
            f"**{fmt_f(ov['rmse'], 2)}**",
            f"**{fmt_pct(ov['within_5_pct'] * 100)}**",
            f"**{fmt_pct(ov['coverage_90'] * 100)}**",
        ]
    )
    return pad_table(rows)


def gen_calibration() -> str:
    notes_inputs = load_reference_notes_inputs()
    training_report = _notes_input_dict(notes_inputs, "training_report")
    cal = training_report.get("calibration_params_sparse_20_balanced")
    if not isinstance(cal, dict):
        raise KeyError(
            "research_summary reference input 'training_report.calibration_params_sparse_20_balanced' missing."
        )
    header = "Calibration regime: `sparse_20_balanced` (domain-balanced, 20 items, 4 per domain).\n\n"
    rows = [["Domain", "Observed Coverage", "Scale Factor"]]
    for d in DOMAIN_ORDER:
        dc = cal[d]
        rows.append(
            [
                DOMAIN_LABELS[d],
                fmt_pct(dc["observed_coverage"] * 100),
                fmt_f(dc["scale_factor"], 1),
            ]
        )
    return header + pad_table(rows)


def gen_domain_balanced_items() -> str:
    notes_inputs = load_reference_notes_inputs()
    item_info = _notes_input_dict(notes_inputs, "item_info")
    items_by_domain: dict[str, list] = defaultdict(list)
    for item in item_info["itemPool"]:
        items_by_domain[item["homeDomain"]].append(item)
    for d in items_by_domain:
        items_by_domain[d].sort(key=lambda x: -x["ownDomainR"])

    rows = [["Rank", "Item", "Domain", "Own-Domain r", "Reverse-Keyed"]]
    rank = 1
    for d in DOMAIN_ORDER:
        for item in items_by_domain[d][:4]:
            rows.append(
                [
                    str(rank),
                    item["id"],
                    DOMAIN_LABELS[d],
                    fmt_r3(item["ownDomainR"]),
                    "yes" if item["isReverseKeyed"] else "no",
                ]
            )
            rank += 1
    return pad_table(rows)


def gen_greedy_ranking() -> str:
    notes_inputs = load_reference_notes_inputs()
    item_info = _notes_input_dict(notes_inputs, "item_info")
    rows = [
        [
            "Rank",
            "Item",
            "Domain",
            "Own-Domain r",
            "Info Score",
            "Ext",
            "Agr",
            "Csn",
            "Est",
            "Opn",
        ]
    ]
    for item in item_info["itemPool"][:20]:
        dc = item["domainCorrelations"]
        rows.append(
            [
                str(item["rank"]),
                item["id"],
                item["homeDomain"],
                fmt_r3(item["ownDomainR"]),
                fmt_f(item["crossDomainInfo"], 3),
                fmt_r3(abs(dc["ext"])),
                fmt_r3(abs(dc["agr"])),
                fmt_r3(abs(dc["csn"])),
                fmt_r3(abs(dc["est"])),
                fmt_r3(abs(dc["opn"])),
            ]
        )
    return pad_table(rows)


def gen_mini_ipip() -> str:
    notes_inputs = load_reference_notes_inputs()
    mapping = _notes_input_dict(notes_inputs, "mini_ipip_mapping")
    domains = mapping["domains"]  # {"Extraversion": ["ext1", "ext7", ...], ...}
    reliability = mapping["reported_reliability"]  # {"Extraversion": 0.77, ...}
    # Map from baseline domain labels to our display labels
    label_map = {
        "Extraversion": "Extraversion",
        "Agreeableness": "Agreeableness",
        "Conscientiousness": "Conscientiousness",
        "EmotionalStability": "Emotional Stability",
        "Intellect": "Intellect/Openness",
    }
    rows = [["Domain", "Items", "Reported Alpha"]]
    for domain_name, item_ids in domains.items():
        label = label_map.get(domain_name, domain_name)
        items_str = ", ".join(item_ids)
        alpha = fmt_f(reliability.get(domain_name, 0), 2)
        rows.append([label, items_str, alpha])
    return pad_table(rows)


def gen_validation_quintiles() -> str:
    """Summarize validate.py quintile-stratified coverage and error.

    This captures distributional behavior (tails vs center), which is otherwise
    lost when only reporting aggregate metrics.
    """
    notes_inputs = load_reference_notes_inputs()
    val = _notes_input_dict(notes_inputs, "validation_results")
    qm = val.get("quintile_metrics", {})

    rows = [["Domain", "Quintile", "n", "MAE", "90% Coverage", "Mean PI Width"]]
    tail_mae, tail_cov, tail_piw = [], [], []
    center_mae, center_cov, center_piw = [], [], []

    for d in DOMAIN_ORDER:
        dqm = qm.get(d, {})
        for q in ["Q1", "Q2", "Q3", "Q4", "Q5"]:
            entry = dqm.get(q)
            if not entry:
                continue
            mae = float(entry.get("mae", 0.0))
            cov = float(entry.get("coverage_90", 0.0)) * 100
            piw = float(entry.get("mean_interval_width", 0.0))
            rows.append(
                [
                    DOMAIN_LABELS[d],
                    q,
                    f"{int(entry.get('n', 0)):,}",
                    fmt_f(mae, 2),
                    fmt_pct(cov),
                    fmt_f(piw, 2),
                ]
            )
            if q in ("Q1", "Q5"):
                tail_mae.append(mae)
                tail_cov.append(cov)
                tail_piw.append(piw)
            elif q == "Q3":
                center_mae.append(mae)
                center_cov.append(cov)
                center_piw.append(piw)

    if tail_mae and center_mae:
        avg = lambda xs: sum(xs) / len(xs)
        rows.append(
            [
                "**Avg Tails (Q1/Q5, all domains)**",
                "---",
                "---",
                f"**{fmt_f(avg(tail_mae), 2)}**",
                f"**{fmt_pct(avg(tail_cov))}**",
                f"**{fmt_f(avg(tail_piw), 2)}**",
            ]
        )
        rows.append(
            [
                "**Avg Center (Q3, all domains)**",
                "---",
                "---",
                f"**{fmt_f(avg(center_mae), 2)}**",
                f"**{fmt_pct(avg(center_cov))}**",
                f"**{fmt_f(avg(center_piw), 2)}**",
            ]
        )

    return pad_table(rows)


def gen_data_splits() -> str:
    """Dataset split sizes and stratification from pipeline stage 04."""
    notes_inputs = load_reference_notes_inputs()
    sm = _notes_input_dict(notes_inputs, "split_metadata")
    rows = [
        ["Split", "Respondents", "Fraction"],
        ["Total valid", f"{sm['total_valid']:,}", "100%"],
        ["Train", f"{sm['train_rows']:,}", fmt_pct(sm["train_frac"] * 100)],
        ["Validation", f"{sm['val_rows']:,}", fmt_pct(sm["val_frac"] * 100)],
        ["Test", f"{sm['test_rows']:,}", fmt_pct(sm["test_frac"] * 100)],
    ]
    header = pad_table(rows)

    strat = (
        f"\n\nStratification: {sm['stratification']} "
        f"({sm['n_strata']} strata, seed={sm['seed']}).\n\n"
    )

    val = sm.get("validation", {})
    if val:
        vrows = [["Domain", "Max Mean Diff", "KS Statistic", "KS p-value"]]
        for d in DOMAIN_ORDER:
            dv = val.get(d, {})
            vrows.append(
                [
                    DOMAIN_LABELS[d],
                    fmt_f(dv.get("max_mean_diff", 0), 4),
                    fmt_f(dv.get("ks_statistic", 0), 4),
                    fmt_f(dv.get("ks_pvalue", 0), 3),
                ]
            )
        strat += pad_table(vrows)

    return header + strat


def gen_training_config() -> str:
    """Training sparsity and augmentation settings from reference config."""
    ref = load_yaml(CONFIGS_DIR / "reference.yaml")
    sp = ref["sparsity"]
    tr = ref["training"]
    va = ref["validation"]
    rows = [
        ["Setting", "Value"],
        ["Config name", ref["name"]],
        ["Sparsity enabled", str(sp["enabled"])],
        ["Focused bucketing", str(sp["focused"])],
        ["Include Mini-IPIP patterns", str(sp["include_mini_ipip"])],
        ["Include imbalanced patterns", str(sp["include_imbalanced"])],
        ["Augmentation passes", str(sp["n_augmentation_passes"])],
        ["CV folds", str(tr["cv_folds"])],
        ["Random state", str(tr["random_state"])],
        ["Min Pearson r gate", fmt_f(va["min_pearson_r"], 2)],
        ["Min 90% coverage gate", fmt_f(va["min_coverage_90"], 2)],
    ]
    return pad_table(rows)


def gen_calibration_policy() -> str:
    """Calibration policy: when each regime is applied."""
    notes_inputs = load_reference_notes_inputs()
    bl = _notes_input_dict(notes_inputs, "baseline_comparison_results")
    policy = bl["config"]["calibration_policy"]
    full_50, sparse, fallback = _resolve_calibration_policy_fields(policy)
    rows = [
        ["Condition", "Calibration Regime"],
        ["50+ items (full scale)", f"`{full_50}`"],
        ["Below 50 items", f"`{sparse}`"],
        ["Fallback (if sparse calibration missing)", f"`{fallback}`"],
    ]
    return pad_table(rows)


def gen_hyperparameter_overrides() -> str:
    """Show manual overrides vs Optuna-tuned values, if any."""
    notes_inputs = load_reference_notes_inputs()
    training_report = _notes_input_dict(notes_inputs, "training_report")
    hp_source = training_report.get("config", {}).get("hyperparameters_source", {})
    overrides = hp_source.get("overrides")
    if not overrides:
        return "*No manual overrides. All hyperparameters as selected by Optuna.*"
    rows = [["Parameter", "Tuned Value", "Used Value"]]
    for param, vals in sorted(overrides.items()):
        rows.append([param, str(vals.get("tuned", "---")), str(vals.get("used", "---"))])
    return pad_table(rows)


def gen_headline_k20() -> str:
    """Key metrics at the K=20 operating point for the abstract."""
    notes_inputs = load_reference_notes_inputs()
    bl = _notes_input_dict(notes_inputs, "baseline_comparison_results")
    comp = _notes_input_dict(notes_inputs, "ml_vs_averaging_comparison")

    k20 = bl["overall"]["20"]
    db = k20["domain_balanced"]
    ca = k20.get("domain_constrained_adaptive", {})
    mi = k20["mini_ipip"]
    at = k20["adaptive_topk"]

    # Find ML-vs-avg deltas at K=20
    db_delta = mi_delta = None
    for e in comp["comparisons"]:
        if e["n_items"] == 20:
            if "domain" in e["method"]:
                db_delta = e
            elif "mini" in e["method"]:
                mi_delta = e

    def ci_str(entry: dict, key: str) -> str:
        ci = entry.get(f"{key}_ci")
        if ci:
            return f" [{fmt_f(ci[0], 4)}, {fmt_f(ci[1], 4)}]"
        return ""

    rows = [
        ["Metric", "Value"],
        [
            "Domain-balanced r",
            f"{fmt_f(db['pearson_r'], 4)}{ci_str(db, 'pearson_r')}",
        ],
        ["Domain-balanced MAE", f"{fmt_f(db['mae'], 2)} pp"],
        ["Domain-balanced 90% coverage", fmt_pct(db["coverage_90"] * 100)],
        [
            "Mini-IPIP r",
            f"{fmt_f(mi['pearson_r'], 4)}{ci_str(mi, 'pearson_r')}",
        ],
        [
            "Constrained-adaptive r",
            f"{fmt_f(ca['pearson_r'], 4)}{ci_str(ca, 'pearson_r')}" if ca else "---",
        ],
        [
            "Adaptive top-K r (greedy)",
            f"{fmt_f(at['pearson_r'], 4)}{ci_str(at, 'pearson_r')}",
        ],
    ]
    if db_delta:
        rows.append(
            [
                "ML vs averaging delta r (domain-balanced)",
                f"{db_delta['delta_r']:+.4f}",
            ]
        )
    if mi_delta:
        rows.append(
            [
                "ML vs averaging delta r (Mini-IPIP)",
                f"{mi_delta['delta_r']:+.4f}",
            ]
        )

    return pad_table(rows)


def gen_ablation_overview() -> str:
    """Cross-variant overview table for research reporting."""
    summary = load_research_summary()
    variants = summary["variants"]

    rows = [
        [
            "Variant",
            "Data Regime",
            "Train Val r (full-50)",
            "Validate r (full-50)",
            "Validate r (sparse-20)",
            "Baselines K20 r (domain-balanced)",
            "Simulation r",
            "Complete",
        ]
    ]

    for variant in VARIANT_ORDER:
        variant_payload = variants.get(variant, {})
        if not isinstance(variant_payload, dict):
            rows.append([VARIANT_LABELS.get(variant, variant)] + ["---"] * 7)
            continue

        rows.append(
            [
                VARIANT_LABELS.get(variant, variant),
                str(variant_payload.get("data_regime", "---")),
                fmt_opt_float(
                    _get_nested(
                        variant_payload,
                        ["training", "validation_full_50", "pearson_r"],
                    ),
                    4,
                ),
                fmt_opt_float(
                    _get_nested(
                        variant_payload,
                        ["validation", "full_50", "pearson_r"],
                    ),
                    4,
                ),
                fmt_opt_float(
                    _get_nested(
                        variant_payload,
                        ["validation", "sparse_20", "pearson_r"],
                    ),
                    4,
                ),
                fmt_opt_float(
                    _get_nested(
                        variant_payload,
                        ["baselines", "k20", "domain_balanced", "pearson_r"],
                    ),
                    4,
                ),
                fmt_opt_float(
                    _get_nested(
                        variant_payload,
                        ["simulation", "overall", "pearson_r"],
                    ),
                    4,
                ),
                "yes" if bool(_get_nested(variant_payload, ["status", "complete"])) else "no",
            ]
        )

    return pad_table(rows)


def gen_ablation_provenance() -> str:
    """Cross-variant provenance locks for auditability."""
    summary = load_research_summary()
    variants = summary["variants"]

    rows = [
        [
            "Variant",
            "Split Signature",
            "Train SHA256",
            "Hyperparams SHA256",
            "Git Hash",
            "Errors",
        ]
    ]

    for variant in VARIANT_ORDER:
        payload = variants.get(variant, {})
        if not isinstance(payload, dict):
            rows.append([VARIANT_LABELS.get(variant, variant)] + ["---"] * 5)
            continue

        split_sig = _get_nested(payload, ["status", "split_signature"])
        train_sha = _get_nested(payload, ["training", "provenance", "train_sha256"])
        hp_sha = _get_nested(payload, ["training", "provenance", "hyperparameters_sha256"])
        git_hash = _get_nested(payload, ["training", "provenance", "git_hash"])
        errors = payload.get("errors", [])
        err_str = "none"
        if isinstance(errors, list) and errors:
            err_str = f"{len(errors)} issue(s)"

        rows.append(
            [
                VARIANT_LABELS.get(variant, variant),
                (split_sig[:12] if isinstance(split_sig, str) else "---"),
                (train_sha[:12] if isinstance(train_sha, str) else "---"),
                (hp_sha[:12] if isinstance(hp_sha, str) else "---"),
                (git_hash[:12] if isinstance(git_hash, str) else "---"),
                err_str,
            ]
        )

    return pad_table(rows)


def _iter_variant_notes_inputs() -> list[tuple[str, str, dict]]:
    records: list[tuple[str, str, dict]] = []
    for variant in VARIANT_ORDER:
        label = VARIANT_LABELS.get(variant, variant)
        notes_inputs = load_variant_notes_inputs(variant)
        records.append((variant, label, notes_inputs))
    return records


def _gen_sparse20_validation_from_notes_inputs(notes_inputs: dict) -> str:
    val = _notes_input_dict(notes_inputs, "validation_results")
    sparse = val.get("sparse_20", {}).get("metrics", {})
    if not isinstance(sparse, dict) or "overall" not in sparse:
        raise KeyError("validation_results.sparse_20.metrics missing.")
    rows = [["Domain", "r", "MAE", "RMSE", "Within-5", "90% Coverage"]]
    for d in DOMAIN_ORDER:
        dm = sparse[d]
        rows.append(
            [
                DOMAIN_LABELS[d],
                fmt_f(dm["pearson_r"], 4),
                fmt_f(dm["mae"], 2),
                fmt_f(dm["rmse"], 2),
                fmt_pct(dm["within_5_pct"] * 100),
                fmt_pct(dm["coverage_90"] * 100),
            ]
        )
    ov = sparse["overall"]
    rows.append(
        [
            "**Overall**",
            f"**{fmt_f(ov['pearson_r'], 4)}**",
            f"**{fmt_f(ov['mae'], 2)}**",
            f"**{fmt_f(ov['rmse'], 2)}**",
            f"**{fmt_pct(ov['within_5_pct'] * 100)}**",
            f"**{fmt_pct(ov['coverage_90'] * 100)}**",
        ]
    )
    return pad_table(rows)


def gen_ablation_validation_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append("**Full-50 validation:**\n")
        parts.append(_gen_validation_from_notes_inputs(notes_inputs))
        parts.append("\n**Sparse-20 validation:**\n")
        parts.append(_gen_sparse20_validation_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


def gen_ablation_baselines_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append(_gen_baselines_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


def gen_ablation_per_domain_k20_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append(_gen_per_domain_k20_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


def gen_ablation_domain_starvation_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append(_gen_domain_starvation_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


def gen_ablation_ml_vs_averaging_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append(_gen_ml_vs_averaging_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


def gen_ablation_simulation_details() -> str:
    parts: list[str] = []
    for _, label, notes_inputs in _iter_variant_notes_inputs():
        parts.append(f"#### {label}\n")
        parts.append(_gen_simulation_from_notes_inputs(notes_inputs))
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Marker replacement
# ---------------------------------------------------------------------------

SECTION_GENERATORS = {
    "data_splits": gen_data_splits,
    "training_config": gen_training_config,
    "model_config": gen_model_config,
    "hyperparameter_overrides": gen_hyperparameter_overrides,
    "norms": gen_norms,
    "calibration_policy": gen_calibration_policy,
    "validation": gen_validation,
    "validation_quintiles": gen_validation_quintiles,
    "baselines": gen_baselines,
    "per_domain_k20": gen_per_domain_k20,
    "domain_starvation": gen_domain_starvation,
    "ml_vs_averaging": gen_ml_vs_averaging,
    "simulation": gen_simulation,
    "calibration": gen_calibration,
    "headline_k20": gen_headline_k20,
    "ablation_overview": gen_ablation_overview,
    "ablation_provenance": gen_ablation_provenance,
    "ablation_validation_details": gen_ablation_validation_details,
    "ablation_baselines_details": gen_ablation_baselines_details,
    "ablation_per_domain_k20_details": gen_ablation_per_domain_k20_details,
    "ablation_domain_starvation_details": gen_ablation_domain_starvation_details,
    "ablation_ml_vs_averaging_details": gen_ablation_ml_vs_averaging_details,
    "ablation_simulation_details": gen_ablation_simulation_details,
    "domain_balanced_items": gen_domain_balanced_items,
    "greedy_ranking": gen_greedy_ranking,
    "mini_ipip": gen_mini_ipip,
}


def update_notes(dry_run: bool = False) -> None:
    if not NOTES_TEMPLATE_PATH.exists():
        print(f"ERROR: Template not found: {NOTES_TEMPLATE_PATH}")
        sys.exit(1)
    text = NOTES_TEMPLATE_PATH.read_text()
    updated = 0
    failed = 0

    for name, gen_fn in SECTION_GENERATORS.items():
        pattern = rf"(<!-- BEGIN:{name} -->\n).*?(\n<!-- END:{name} -->)"
        if not re.search(pattern, text, flags=re.DOTALL):
            print(f"  SKIP  {name} (no markers found in NOTES.md)")
            continue
        try:
            content = gen_fn()
            replacement = rf"\g<1>{content}\g<2>"
            text = re.sub(pattern, replacement, text, flags=re.DOTALL)
            updated += 1
            if dry_run:
                print(f"\n--- {name} ---")
                print(content)
            else:
                print(f"  OK    {name}")
        except Exception as e:
            print(f"  FAIL  {name}: {e}")
            failed += 1

    if failed:
        print(f"\nWARNING: {failed} sections failed to generate — file not written")
        sys.exit(1)

    if not dry_run:
        NOTES_PATH.write_text(text)
        print(f"\nUpdated {updated} sections in {NOTES_PATH.relative_to(PACKAGE_ROOT)}")
    else:
        print(f"\nDry run: {updated} sections would be updated")


def main() -> None:
    parser = argparse.ArgumentParser(description="Update data sections in NOTES.md")
    parser.add_argument(
        "--dry-run", action="store_true", help="Print sections without writing"
    )
    args = parser.parse_args()
    update_notes(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
